homeassistant:
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
device_tracker: !include device_tracker.yaml
lovelace: !include lovelace.yaml
light: !include lights.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
input_select: !include input_selects.yaml
input_boolean: !include input_booleans.yaml
input_datetime: !include input_datetimes.yaml
input_number: !include input_numbers.yaml

# Loosen up on the logging
logger:
  default: error
  # default: info
  # default: critical

# Set recording parts
recorder:
  purge_keep_days: 15
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - media_player
    entities:
      - sun.sun           # Don't record sun data
      - sensor.last_boot  # Comes from 'systemmonitor' sensor platform
      - sensor.date

# Enable theming support
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

#Integrated config editor
config_editor:

# Spotify cast integration
spotcast:
  sp_dc: !secret primary_sp_dc
  sp_key: !secret primary_sp_key
  country: SE
  accounts:
    haqwin:
      sp_dc: !secret haqwin_sp_dc
      sp_key: !secret haqwin_sp_key
    family:
      sp_dc: !secret family_sp_dc
      sp_key: !secret family_sp_key
